### ISSUE TITLE
[FEATURE] Add setting to disable the outer ring resizing when you get it correct. (un:safe)

### ISSUE THREAD

**Issue by paytondevs** [roblack/workshop#1]
**Is your feature request related to a problem? Please describe.**
I think the game is slightly too easy, and would be more fun for some people if you could (optionally) disable the outer ring resizing.

**Describe the solution you'd like**
--
Add a settings menu or a secret code (ex. tapping the 3 dots in the bottom right, something most people probably wouldn't do) that disables this mechanic, and makes the game purely based on haptics instead of visuals.
**don't forget to select a project on the right side 👉**

**Comment by ajimix** [comment]
+1 please. The game is very easy and not enjoyable with the visual feedback. If should give option to play only with taptic feedback

**Comment by emin-grbo** [comment]
Love this! 🥳 will make it happen soon!!

**Comment by emin-grbo** [comment]
Done and DONE 🙌

Uploading now and releasing new version as soon as it is approved.

@paytontech , As the first-ever feature req I will be sending you some promo codes to use. I know the app is free now, but it will be $4.99 in a day or two, so you can share that with whoever you want.

I know it's not much, but its at least a way I can show some appreciation 👍 
@ajimix , I got you covered as well 🎟

![image](https://user-images.githubusercontent.com/21968377/146690718-b8060a43-bd19-4654-926e-bfb5696a5030.png)
