### ISSUE TITLE
[FEATURE] GameCenter Integration

### ISSUE THREAD

**Issue by jsulgrove** [roblack/workshop#2]
Integrate GameCenter into the app. This will allow for a leaderboard, in which I can compare with friends and other players. (This would also mean numbering the levels beyond 50)

**Comment by emin-grbo** [comment]
This is interesting. I never thought people use game center as much 🤷‍♂️ 
Good idea either way, will put this on the roadmap 👌

**Comment by emin-grbo** [comment]
Done and done!
