### ISSUE TITLE
[FEATURE] countdown timer on higher levels

### ISSUE THREAD

**Issue by billipo** [roblack/workshop#6]
I completed the first 20 levels after I got a feel for the game. I expected to encounter some nuance and increasing difficulty after the first 10 levels, but it was more of the same.

I think you could introduce some complexity through a countdown timer. This would fit well with your theme of cracking a lock. Maybe at level 10, the countdown timer is set for five minutes. At higher levels, it could be down around one minute for level.

**don't forget to select a project on the right side 👉**

**Comment by emin-grbo** [comment]
Oh right, thank you for that feedback! 🙌

I did plan to add the timer but never expected the game to blow up as fast as it did :) 

That sounds like a very good suggestion, will incorporate it for sure.

I also had an idea of a "reset" timer. In a sense that the combo needed gets refreshed after a certain interval. That way you don't really "lose" if the timer is out, but you can start solving it again! 

What do you think about that approach @billipo ?

**Comment by billipo** [comment]
I'm a fan of games that are unforgiving but playable. I've been a little obsessed with Blackbox on iOS recently. It's the perfect combination of difficulty and mystery. I think your app has an excellent idea, and your implementation is really nice. I'd love to discuss some ideas for how it could keep players interested and involved. I would prefer that the timer not have a reset function, because the game starting over is the consequence. However, I could see a "Save" function that allows players to be able to start over at level 11, instead of level 1 when they fail. Saves could also be a good way to get in-app purchases. Maybe players start with 3 saves and have to earn more by unlocking them. Players would have to choose at which level to use each of their saves, and they might have to purchase more saves if they run out. The unlocking theme of your game is actually great for rewarding players as they progress. Let's discuss more! My email is billipo @ gmail

**Comment by billipo** [comment]
I forgot to mention that I don't have an Apple Watch, so I'm grateful for your iPhone port. It works really well on my iPhone 13. I haven't tried it on any other devices.

**Comment by emin-grbo** [comment]
That sounds very interesting man! Will drop an email 🙌

**Comment by emin-grbo** [comment]
FYI I forgot to update this spot, but added it in the latest release :) 🙌
